version: '3.8'
services:
  websocket:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8788:8080"
    environment:
      NODE_ENV: development
    volumes:
      - ${CERT}:/app/cert.pem
      - ${KEY}:/app/key.pem
    env_file:
      - .env